### ISSUE TITLE
ERROR Error: Cannot find module 'C:\[PATH]/tailwind.config.js'

### ISSUE THREAD

**Issue by christophervlapa** [ecklf/tailwind.json#5]
`npx tailwind.json` command does not work on Next 13.4.19 with Tailwind 3.3.3 with NodeJS v18.16.0 as the `tailwind.config.js` is `tailwind.config.ts` now, and so produces error:

```
npx tailwind.json
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\[PATH]/tailwind.config.js'
Require stack:
- C:\[PATH]\AppData\Local\npm-cache\_npx\24734350847605ee\node_modules\tailwind.json\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\[PATH]\AppData\Local\npm-cache\_npx\24734350847605ee\node_modules\tailwind.json\index.js:5:24)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\[PATH]\\AppData\\Local\\npm-cache\\_npx\\24734350847605ee\\node_modules\\tailwind.json\\index.js'
  ]
}

Node.js v18.16.0
```

This can be fixed on line 5 of `index.js` perhaps using `fs.existsSync()`?
